# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hackbright Journey
email: terriwmj@gmail.com
description: # this means to ignore newlines until "baseurl:"
  Hackbright Journey happening in San Francisco. 
  A Cognitive Branding Designer evolving to Software Engineer. 
  Design, Python, HCI.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://terriwong.github.io" # the base hostname & protocol for your site
twitter_username: terriwonglee
github_username:  terriwong

# Build settings
markdown: kramdown
